name: Ambros CI Build Dev

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: 
  group: ios-build-dev
  cancel-in-progress: true

env:
  LANG: en_US.UTF-8
  
jobs:
  clone-and-build:
    runs-on: macos-12
    environment: main
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get configuration items
        run: |
          echo $SSH_PRIVATE_KEY | base64 --decode > private.key

          chmod 600 private.key
          pwd
          ls -al
          rm -rf $HOME/ambros-mobile

          GIT_SSH_COMMAND='ssh -i private.key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no' git clone git@github.com:Ambros-Technology/ambros-mobile.git $HOME/ambros-mobile

          
          rm -rf $HOME/ambros-mobile-enviroment

          GIT_SSH_COMMAND='ssh -i private.key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no' git clone git@github.com:Ambros-Technology/ambros-mobile-enviroment.git $HOME/ambros-mobile-enviroment
          
