name: Ambros iOS CI Prod

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ios_ci_prod]

concurrency: 
  group: iOS-build-prod
  cancel-in-progress: true

env:
  LANG: en_US.UTF-8
  
jobs:
  clone-and-build:
    runs-on: macos-12
    environment: main
    env:
      AMBROS_MOBILE_SSH_PRIVATE_KEY: ${{ secrets.AMBROS_MOBILE_SSH_PRIVATE_KEY }}
      AMBROS_MOBILES_KEYS_SSH_PRIVATE_KEY: ${{ secrets.AMBROS_MOBILES_KEYS_SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get configuration items
        env:
          MOBILE_KEYS_SSH_PRIVATEKEY: ${{ secrets.MOBILE_KEYS_SSH_PRIVATEKEY }}
          AMBROS_MOBILE_KEY_PASSPHRASE: ${{ secrets.AMBROS_MOBILE_KEY_PASSPHRASE }}

        run: |
          echo "Home: " $HOME
          echo $AMBROS_MOBILE_SSH_PRIVATE_KEY | base64 --decode > AMBROS_MOBILE_SSH_PRIVATE_KEY.key
          chmod 600 AMBROS_MOBILE_SSH_PRIVATE_KEY.key
          echo $AMBROS_MOBILES_KEYS_SSH_PRIVATE_KEY | base64 --decode > AMBROS_MOBILES_KEYS_SSH_PRIVATE_KEY.key
          chmod 600 AMBROS_MOBILES_KEYS_SSH_PRIVATE_KEY.key
          rm -rf $HOME/ambros_mobile

          AMBROX_MOBILE_BRANCH="develop" 
          # TODO : need to change this branch to the input branch
          
          GIT_SSH_COMMAND='ssh -i AMBROS_MOBILE_SSH_PRIVATE_KEY.key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no' git clone -b $AMBROX_MOBILE_BRANCH git@github.com:Ambros-Technology/ambros_mobile.git $HOME/ambros_mobile
          rm -rf $HOME/ambros_mobiles_keys
          GIT_SSH_COMMAND='ssh -i AMBROS_MOBILES_KEYS_SSH_PRIVATE_KEY.key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no' git clone git@github.com:Ambros-Technology/ambros_mobiles_keys.git $HOME/ambros_mobiles_keys
          CONFIG_PATH=$HOME/ambros_mobiles_keys
          echo $CONFIG_PATH
          echo "Using gpg to decrypt sensitive files now"
          gpg --quiet --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/sentry.android.properties.gpg > $CONFIG_PATH/sentry.android.properties
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/sentry.ios.properties.gpg > $CONFIG_PATH/sentry.ios.properties
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/.env.android.gpg > $CONFIG_PATH/.env.android 
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/.env.ios.gpg > $CONFIG_PATH/.env.ios
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/ios/code-push.xcconfig.gpg > $CONFIG_PATH/ios/code-push.xcconfig
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/ios/fastlane/.env.ios.gpg > $CONFIG_PATH/ios/fastlane/.env.ios
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/android/fastlane/.env.android.gpg > $CONFIG_PATH/android/fastlane/.env.android 
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/keys/android-keys/ambros-portal-dev.jks.gpg > $CONFIG_PATH/keys/android-keys/ambros-portal-dev.jks
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/keys/android-keys/ambros-portal-prod.jks.gpg > $CONFIG_PATH/keys/android-keys/ambros-portal-prod.jks
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/keys/ios-keys/certificate/Ambros\ Technology\ -\ Cer\ -\ Ad\ Hoc.p12.gpg > $CONFIG_PATH/keys/ios-keys/certificate/Ambros-Technology-Cer-Ad-Hoc.p12
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/keys/ios-keys/certificate/Michael\ Nguyen\ -\ Cer\ -\ Dev.p12.gpg > $CONFIG_PATH/keys/ios-keys/certificate/Michael-Nguyen-Cer-Dev.p12
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/keys/ios-keys/provisioning-profile/Ambros_Portal_Dev.mobileprovision.gpg > $CONFIG_PATH/keys/ios-keys/provisioning-profile/Ambros_Portal_Dev.mobileprovision 
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/keys/ios-keys/provisioning-profile/Ambros_Portal_Dev_Ad_Hoc.mobileprovision.gpg > $CONFIG_PATH/keys/ios-keys/provisioning-profile/Ambros_Portal_Dev_Ad_Hoc.mobileprovision 
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/keys/ios-keys/provisioning-profile/Ambros_Portal_Prod.mobileprovision.gpg > $CONFIG_PATH/keys/ios-keys/provisioning-profile/Ambros_Portal_Prod.mobileprovision
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/keys/ios-keys/provisioning-profile/Ambros_Portal_Prod_Ad_Hoc.mobileprovision.gpg > $CONFIG_PATH/keys/ios-keys/provisioning-profile/Ambros_Portal_Prod_Ad_Hoc.mobileprovision 
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/keys/ios-keys/provisioning-profile/BcmHunt_WildCard_Ad_Hoc.mobileprovision.gpg > $CONFIG_PATH/keys/ios-keys/provisioning-profile/BcmHunt_WildCard_Ad_Hoc.mobileprovision
          gpg --batch --batch --yes --decrypt --passphrase=$AMBROS_MOBILE_KEY_PASSPHRASE $CONFIG_PATH/keys/ios-keys/provisioning-profile/BcmHunt_WildCard_Dev.mobileprovision.gpg > $CONFIG_PATH/keys/ios-keys/provisioning-profile/BcmHunt_WildCard_Dev.mobileprovision

          # 3. Copy file .env.android, .env.ios, sentry.android.properties, sentry.ios.properties to folder of  project ambros_mobile
          cp $CONFIG_PATH/sentry.android.properties $HOME/ambros_mobile/sentry.android.properties
          cp $CONFIG_PATH/sentry.ios.properties $HOME/ambros_mobile/sentry.ios.properties
          cp $CONFIG_PATH/.env.android $HOME/ambros_mobile/.env.android
          cp $CONFIG_PATH/.env.ios $HOME/ambros_mobile/.env.ios

          # 4. Copy file android/fastlane/.env.android to folder android/fastlane of project ambros_mobile
          cp $CONFIG_PATH/android/fastlane/.env.android $HOME/ambros_mobile/android/fastlane/.env.android

          # 5. Copy file ios/code-push.xcconfig to folder ios/ of project ambros_mobile
          cp $CONFIG_PATH/ios/code-push.xcconfig $HOME/ambros_mobile/ios/code-push.xcconfig
          
          # 6. Copy file ios/fastlane/.env.ios to folder ios/fastlane of project ambros_mobile
          cp $CONFIG_PATH/ios/fastlane/.env.ios $HOME/ambros_mobile/ios/fastlane/.env.ios

      - name: Install brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Node and Watchman
        run: |
          brew install node
          brew install watchman

      - name: Yarn setup
        run: yarn setup
        working-directory: /Users/runner/ambros_mobile

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Install Fastlane
        run: gem install fastlane
        working-directory: /Users/runner/ambros_mobile

      - name: Setup cache
        uses: actions/cache@v1
        with:
          path: Pods
          key: ${{ runner.os }}-ios-build-cache
          restore-keys: |
            ${{ runner.os }}-ios-build-cache

      - name: Fastlane action
        uses: maierj/fastlane-action@v2.3.0
        env:

          APP_CENTER_API_TOKEN_PROD: ${{ secrets.IOS_APP_CENTER_API_TOKEN_PROD }}
          CODE_PUSH_KEY_PROD: ${{ secrets.IOS_CODE_PUSH_KEY_PROD }}
          SENTRY_INTERNAL_DSN: ${{ secrets.IOS_SENTRY_INTERNAL_DSN }}
          BCMHUNT_WILDCARD_AD_HOC_PATH: /Users/runner/ambros_mobiles_keys/keys/ios-keys/provisioning-profile/BcmHunt_WildCard_Ad_Hoc.mobileprovision
          AMBROS_PORTAL_DEV_PATH: /Users/runner/ambros_mobiles_keys/keys/ios-keys/provisioning-profile/Ambros_Portal_Dev.mobileprovision
          BCMHUNT_WILDCARD_DEV_PATH: /Users/runner/ambros_mobiles_keys/keys/ios-keys/provisioning-profile/BcmHunt_WildCard_Dev.mobileprovision
          AMBROS_PORTAL_DEV_AD_HOC_PATH: /Users/runner/ambros_mobiles_keys/keys/ios-keys/provisioning-profile/Ambros_Portal_Dev_Ad_Hoc.mobileprovision
          AMBROS_PORTAL_PROD_PATH: /Users/runner/ambros_mobiles_keys/keys/ios-keys/provisioning-profile/Ambros_Portal_Prod.mobileprovision
          AMBROS_PORTAL_PROD_AD_HOC_PATH: /Users/runner/ambros_mobiles_keys/keys/ios-keys/provisioning-profile/Ambros_Portal_Prod_Ad_Hoc.mobileprovision 
          
          DEV_CERT_PATH: /Users/runner/ambros_mobiles_keys/keys/ios-keys/certificate/Michael-Nguyen-Cer-Dev.p12
          DEV_CERT_PASSWORD: ${{ secrets.DEV_CERT_PASSWORD }}           
          ADHOC_CERT_PATH: /Users/runner/ambros_mobiles_keys/keys/ios-keys/certificate/Ambros-Technology-Cer-Ad-Hoc.p12
          ADHOC_CERT_PASSWORD: ${{ secrets.ADHOC_CERT_PASSWORD }}   

        with:
          lane: prod_ci
          subdirectory: ../../../ambros_mobile/ios

